openapi: 3.1.0
info:
  title: Example
  description: Example API description
  contact:
    name: Binary Birds
    url: https://binarybirds.com
    email: info@binarybirds.com
  version: 1.0.0
tags:
- name: Model
  description: ''
servers:
- url: http://localhost:8080
  description: dev
paths:
  /example/models:
    post:
      tags:
      - Model
      summary: Create example
      description: Create example detail
      operationId: createExampleModel
      requestBody:
        description: Create example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleModelCreate'
        required: true
      responses:
        200:
          $ref: '#/components/responses/ExampleModelDetail'
      security:
      - ExampleModelBearerToken: []
  /example/models/{id}:
    parameters:
    - $ref: '#/components/parameters/ExampleModelId'
    get:
      tags:
      - Model
      summary: Detail example
      description: Detail example detail
      operationId: getExampleModel
      responses:
        200:
          $ref: '#/components/responses/ExampleModelDetail'
      security: []
components:
  schemas:
    ExampleModelId:
      type: string
      format: uuid
      description: Unique example model identifier
      examples:
      - EADC8E71-DBEA-4E97-8583-3F9868DB131A
      - 394E4D2E-6DD5-4E02-9BB6-8626DBF28EB9
      - 0715DC92-C02D-41D5-AFFC-C330069943CD
      - 69854148-674A-4EE9-87E8-3CFF58046473
      - 69561227-B47D-4ADE-9337-635AD83C7E40
    ExampleModelKey:
      type: string
      description: Key of the example model
      examples:
      - my-example-key
    ExampleModelCreate:
      type: object
      description: example model create object
      properties:
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - key
    ExampleModelPatch:
      type: object
      description: example model detail object
      properties:
        key:
          $ref: '#/components/schemas/ExampleModelKey'
    ExampleModelDetail:
      type: object
      description: example model detail object
      properties:
        id:
          $ref: '#/components/schemas/ExampleModelId'
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - id
      - key
    ExampleModelList:
      type: array
      description: Lorem ipsum dolor sit amet
      items:
        $ref: '#/components/schemas/ExampleModelListItem'
      maxItems: 1000
      minItems: 0
    ExampleModelListItem:
      type: object
      description: example model detail object
      properties:
        id:
          $ref: '#/components/schemas/ExampleModelId'
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - id
      - key
  responses:
    ExampleModelDetail:
      description: Example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleModelDetail'
  parameters:
    ExampleModelId:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/ExampleModelId'
      description: Example parameter
  requestBodies:
    ExampleModelCreate:
      description: Create example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleModelCreate'
      required: true
  headers:
    X-Custom-Header:
      schema:
        type: string
        title: Custom header
        description: Custom header description
  securitySchemes:
    ExampleModelBearerToken:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
