openapi: 3.1.0
info:
  title: Example
  description: Example API description
  contact:
    name: Binary Birds
    url: https://binarybirds.com
    email: info@binarybirds.com
  version: 1.0.0
tags:
- name: Model
  description: ''
servers:
- url: http://localhost:8080
  description: dev
paths:
  /example/models:
    post:
      tags:
      - Model
      summary: Create example
      description: Create example detail
      operationId: createExampleModel
      requestBody:
        description: Create example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleModelCreate'
        required: true
      responses:
        200:
          $ref: '#/components/responses/ExampleModelDetail'
      security:
      - ExampleModelBearerToken: []
  /example/models/{id}:
    parameters:
    - $ref: '#/components/parameters/ExampleModelId'
    get:
      tags:
      - Model
      summary: Detail example
      description: Detail example detail
      operationId: getExampleModel
      responses:
        200:
          $ref: '#/components/responses/ExampleModelDetail'
      security: []
components:
  schemas:
    ExampleModelId:
      type: string
      format: uuid
      description: Unique example model identifier
      examples:
      - 124C8F79-CD5B-4D41-A732-76B42C01705E
      - B45AA57C-88B7-40B6-B53D-DA0411B4E7DC
      - FBBC78B0-4E6C-44B9-B6FC-6B2E6393204B
      - AEB84B3F-F93D-495D-AEA5-A7636112ED8F
      - BD9DF1DE-F13E-4BD4-A082-C3F357307BF9
    ExampleModelKey:
      type: string
      description: Key of the example model
      examples:
      - my-example-key
    ExampleModelCreate:
      type: object
      description: example model create object
      properties:
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - key
    ExampleModelDetail:
      type: object
      description: example model detail object
      properties:
        id:
          $ref: '#/components/schemas/ExampleModelId'
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - id
      - key
    ExampleModelList:
      type: array
      description: Lorem ipsum dolor sit amet
      items:
        $ref: '#/components/schemas/ExampleModelListItem'
      maxItems: 1000
      minItems: 0
    ExampleModelListItem:
      type: object
      description: example model detail object
      properties:
        id:
          $ref: '#/components/schemas/ExampleModelId'
        key:
          $ref: '#/components/schemas/ExampleModelKey'
      required:
      - id
      - key
  responses:
    ExampleModelDetail:
      description: Example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleModelDetail'
  parameters:
    ExampleModelId:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/ExampleModelId'
      description: Example parameter
  requestBodies:
    ExampleModelCreate:
      description: Create example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExampleModelCreate'
      required: true
  headers:
    X-Custom-Header:
      schema:
        type: string
        title: Custom header
        description: Custom header description
  securitySchemes:
    ExampleModelBearerToken:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
