openapi: 3.1.0
info:
  title: Example
  description: Example API description
  contact:
    name: Binary Birds
    url: https://binarybirds.com
    email: info@binarybirds.com
  version: 1.0.0
tags:
- name: Model
  description: ''
servers:
- url: http://localhost:8080
  description: dev
paths:
  /example/models:
    post:
      tags:
      - Model
      summary: Create example
      description: Create example detail
      operationId: CreateOperationsModelExampleFeatherOpenAPIKitTests
      requestBody:
        description: Create example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelSchemasCreate'
        required: true
      responses:
        200:
          $ref: '#/components/responses/FeatherOpenAPIKitTestsExampleModelResponsesDetail'
      security:
      - FeatherOpenAPIKitTestsExampleModelSecuritySchemesBearerToken: []
  /example/models/{id}:
    parameters:
    - $ref: '#/components/parameters/FeatherOpenAPIKitTestsExampleModelParametersId'
    get:
      tags:
      - Model
      summary: List example
      description: List example detail
      operationId: GetOperationsModelExampleFeatherOpenAPIKitTests
      responses:
        200:
          $ref: '#/components/responses/FeatherOpenAPIKitTestsExampleModelResponsesDetail'
      security:
      - FeatherOpenAPIKitTestsExampleModelSecuritySchemesBearerToken: []
components:
  schemas:
    FeatherOpenAPIKitTestsExampleModelFieldsId:
      type: string
      format: uuid
      description: Unique system variable identifier
      examples:
      - 4B497957-88D3-4BF8-8030-62E2D92028E4
      - 3237E470-2C0E-44DF-8C89-92355A0809E6
      - E2022792-163A-4F6E-BC10-9B276A48D257
      - F9A1C2D8-837A-4625-97AF-74186B470F7C
      - EA8B5792-2D8D-4190-86D2-CEFDAEE6B896
    FeatherOpenAPIKitTestsExampleModelFieldsKey:
      type: string
      description: Key of the system variable
      examples:
      - systemEmailAddress
    FeatherOpenAPIKitTestsExampleModelSchemasCreate:
      type: object
      properties:
        key:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelFieldsKey'
      required:
      - key
    FeatherOpenAPIKitTestsExampleModelSchemasDetail:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelFieldsId'
        key:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelFieldsKey'
      required:
      - id
      - key
  responses:
    FeatherOpenAPIKitTestsExampleModelResponsesDetail:
      description: Example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelSchemasDetail'
  parameters:
    FeatherOpenAPIKitTestsExampleModelParametersId:
      name: id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelFieldsId'
      description: Example parameter
  requestBodies:
    FeatherOpenAPIKitTestsExampleModelRequestBodiesCreate:
      description: Create example
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleModelSchemasCreate'
      required: true
  headers:
    X-Custom-Header:
      schema:
        type: string
        title: Custom header
        description: custom header description
  securitySchemes:
    FeatherOpenAPIKitTestsExampleModelSecuritySchemesBearerToken:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
