openapi: 3.1.0
info:
  title: Example
  description: Example API description
  contact:
    name: Binary Birds
    url: https://binarybirds.com
    email: info@binarybirds.com
  version: 1.0.0
tags:
- name: FeatherOpenAPIKitTestsExampleTag
  description: ''
- name: FeatherOpenAPIKitTestsFooTag
  description: ''
servers:
- url: http://localhost:8080
  description: dev
paths:
  /example/{exampleId}:
    summary: path summary
    description: path description
    parameters:
    - $ref: '#/components/parameters/FeatherOpenAPIKitTestsExampleParameter'
    get:
      tags:
      - FeatherOpenAPIKitTestsExampleTag
      summary: List profiles
      description: List available profiles
      operationId: FeatherOpenAPIKitTestsExampleOperation
      parameters:
      - $ref: '#/components/parameters/FeatherOpenAPIKitTestsExampleParameter'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooSchema'
        400:
          $ref: '#/components/responses/FeatherOpenAPIKitTestsExampleResponse'
      security:
      - FeatherOpenAPIKitTestsExampleSecurityScheme: []
  /foo/{fooId}:
    summary: path summary
    description: path description
    parameters:
    - $ref: '#/components/parameters/FeatherOpenAPIKitTestsFooParameter'
    get:
      tags:
      - FeatherOpenAPIKitTestsFooField
      summary: List profiles
      description: List available profiles
      operationId: FeatherOpenAPIKitTestsFooOperation
      parameters:
      - $ref: '#/components/parameters/FeatherOpenAPIKitTestsFooParameter'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooSchema'
        400:
          $ref: '#/components/responses/FeatherOpenAPIKitTestsFooResponse'
      security: []
components:
  schemas:
    FeatherOpenAPIKitTestsExampleField:
      type: string
    FeatherOpenAPIKitTestsExampleSchema:
      type: object
      properties:
        example:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleField'
      required:
      - example
    FeatherOpenAPIKitTestsFooField:
      type: string
    FeatherOpenAPIKitTestsFooSchema:
      type: object
      properties:
        foo:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooField'
        bar:
          $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooField'
        baz:
          type: string
      required:
      - bar
      - baz
  responses:
    FeatherOpenAPIKitTestsExampleResponse:
      description: lorem ipsum
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleSchema'
    FeatherOpenAPIKitTestsFooResponse:
      description: lorem ipsum
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooSchema'
  parameters:
    FeatherOpenAPIKitTestsExampleParameter:
      name: exampleId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleSchema'
      description: example parameter
    FeatherOpenAPIKitTestsFooParameter:
      name: fooId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/FeatherOpenAPIKitTestsFooField'
  requestBodies:
    FeatherOpenAPIKitTestsExampleRequestBody:
      description: Example request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FeatherOpenAPIKitTestsExampleSchema'
      required: true
  headers:
    X-Example-Header:
      schema:
        type: string
        title: Example header
        description: test
    X-Foo-Header:
      schema:
        type: integer
        title: Foo header
        description: test
  securitySchemes:
    FeatherOpenAPIKitTestsExampleSecurityScheme:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
    FeatherOpenAPIKitTestsFooSecurityScheme:
      description: Authorization header using a Bearer token
      type: http
      scheme: bearer
      bearerFormat: token
